CONFIG_I2C=n
CONFIG_GPIO_PCA_SERIES=n

CONFIG_LOG=y
CONFIG_MCUBOOT_LOG_LEVEL_DBG=y

# this 3 items not here, at ../sysbuild.conf
# CONFIG_BOOT_UPGRADE_ONLY=n
# CONFIG_BOOT_SWAP_USING_SCRATCH=n
# CONFIG_BOOT_SWAP_USING_MOVE=y

