# ----> build/mcuboot/zephyr/.config.sysbuild
SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y
# SB_CONFIG_MCUBOOT_MODE_SWAP_USING_MOVE=y
# DIRECT_XIP will build two image for slot0 and slot1 for diff ADDR off 
# SB_CONFIG_MCUBOOT_MODE_DIRECT_XIP=y
# SB_CONFIG_MCUBOOT_MODE_DIRECT_XIP_WITH_REVERT=y
