CONFIG_WIFI_ESP32=y

# apsta_mode configuration
#CONFIG_WIFI_SAMPLE_SSID="ACX2"
#CONFIG_WIFI_SAMPLE_PSK="reinao802"
CONFIG_WIFI_SAMPLE_SSID="AX2"
CONFIG_WIFI_SAMPLE_PSK="12345678"
CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.168.66.228"
